### ISSUE TITLE
Singlerecipe parameter not working

### ISSUE THREAD

**Issue by nathangraham-MSFT** [asjimene/CMPackager#134]
Using the latest version of CMPackager.ps1, -singlerecipe parameter is broken because $PSScriptRoot (line 31 & line 39) is not enumerating. $PSScriptRoot is $null so line 48 fails due to the path not resolving.

**Comment by theaquamarine** [comment]
I think the issue is because [the `ValidateSet` for `SingleRecipe` is relies on the value of `$RecipePath`](https://github.com/asjimene/CMPackager/blob/8241abab5c8153c3b22908d957006b53551ed391/CMPackager.ps1#L48), which is [only set after non-dynamic parameters are evaluated](https://github.com/asjimene/CMPackager/blob/8241abab5c8153c3b22908d957006b53551ed391/CMPackager.ps1#L39) if `-RecipePath` isn't set on the command line (see [here](https://stackoverflow.com/questions/65221816/dynamic-parameters-in-powershell-based-on-value-of-other-parameter) for a similar issue).

![image](https://github.com/asjimene/CMPackager/assets/111144/61f39268-7272-4c02-ab66-64410dc6ce38)

As a temporary workaround, specifying `-RecipePath` too allows it to work.

A more permanent fix could be check if `$RecipePath` is set when getting the list of files for the `ValidateSet` and using the default `$PSSscriptRoot\Recipes` if not? It's a bit convoluted, but the only other option that leaps to mind is make them both dynamic parameters. https://github.com/asjimene/CMPackager/blob/8241abab5c8153c3b22908d957006b53551ed391/CMPackager.ps1#L48

![image](https://github.com/asjimene/CMPackager/assets/111144/5bf40471-d5ac-4d63-b575-11d4c2dc4f01)
