### ISSUE TITLE
Question about use

### ISSUE THREAD

**Issue by jonnwhite1** [asjimene/CMPackager#36]
Hey!

Thank you for developing this fantastic tool!
I've been using it a while now and have two questions, I'm not sure if they are already features or whether I need to request them as enhancements?

1, How do I provide SMTP authentication? SMTP server requires authentication and I can't work this one out or if it is possible.

2, Deployment type, I have Auto deployment turned on to a collection, is there a way I can specify the deployment to be Required rather than Available? I have supercendence and for some apps EG Chrome, I would like to force the new version out to people.

Following on from question to is there a way I can make a required deployment to one collection by available to another? EG Two collections, all PC's and All PC's with chrome installed. Is there a way to make available to all PC's and required to All PC's With chrome?

Thank you for your hard work!

Jon

**Comment by asjimene** [comment]
1. I never implemented SMTP authentication in the script, feel free to dig around the "Send-EmailMessage" function in the script and see if you can add it.

2. You can modify this in the script as well, check out the "Invoke-ApplicationDeployment" function and just modify the deployment command to be required instead of available.

Adding a second deployment is an interesting idea, I'll may look into that in the future.
